import React from "react";
import TopHeader from "../TopHeader";
import ContainerGrid from "../ContainerGrid";
import Head from "next/head";
import Footer from "../Footer";
import TheHeader from "../Header";
import MenuHeader from "../MenuHeader";
import { CardProvider } from "../../context/storeContext";
import { ProductsProvider } from "../../context/productContext";
import CarouselProduct from "../CarouselProduct";

type LayoutProps = {
  children: React.ReactNode;
};

export const Layout = ({ children }: LayoutProps) => {
  return (
    <CardProvider>
      <ProductsProvider>
        <main>
          <Head>
            <title>Ecommerce-app</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
          </Head>
          <TopHeader />
          <ContainerGrid>
            <TheHeader />
            <MenuHeader />
            <CarouselProduct />
            {children}
            <Footer />
          </ContainerGrid>
        </main>
      </ProductsProvider>
    </CardProvider>
  );
};
