import Head from 'next/head'
import { GlobalStyle } from "../styles/global"
import TopHeader from "../components/TopHeader"
import ContainerGrid from "../components/ContainerGrid"
import MenuHeader from '../components/MenuHeader'
import Carousel from "../components/CarouselProduct"
import TheHeader from "../components/TheHeader/TheHeader"
import PromotionCard from "../components/PromotionCard"
import ProductsList from "../components/ProductsList"
import Footer from "../components/Footer"
import CartSideBar from "../components/CartSidebar"


export default function Home() {

  
  return (
    <>
      <Head>
        <title>Ecommerce-app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <TopHeader />
        <ContainerGrid>
          <TheHeader />
          <MenuHeader />
        </ContainerGrid>
        <Carousel />
        <ContainerGrid>
          <PromotionCard />
          <ProductsList />
        </ContainerGrid>
      </main>
      <Footer />
      <GlobalStyle />
    </>
  )
}
